const mongoose = require("mongoose");
const Booking = require("../models/Booking");
const User = require("../models/User");
const { ok, fail } = require("../utils/response");
const ah = require("../utils/asyncHandler");
const logger = require("../services/logger");
const eventHub = require("../services/eventHub");
const { generateWalkinPass } = require("../utils/walkinPassPDF");

const ACTIVE_STATUSES = ["PENDING_ASSISTANT", "CONFIRMED", "PATIENT_ARRIVED", "IN_TREATMENT"];

function generateWalkinTokenId() {
  return `QX-${Math.floor(8000 + Math.random() * 1000)}`;
}

async function uniqueWalkinTokenId() {
  for (let i = 0; i < 10; i++) {
    const candidate = generateWalkinTokenId();
    const exists = await Booking.findOne({ tokenId: candidate });
    if (!exists) return candidate;
  }
  return `QX-${8000 + Math.floor(Math.random() * 1000)}`;
}

exports.createWalkinToken = ah(async (req, res) => {
  const { patientName, patientMobile, patientAge, patientEmail, symptoms, doctorName, doctorDept, slotTime, bookingDate } = req.body;

  if (!patientName || !patientMobile) {
    return fail(res, "Patient name and mobile number are required", 422);
  }

  const today = bookingDate || new Date().toISOString().split("T")[0];
  const timeSlot = slotTime || "09:00 AM - 11:00 AM";

  const existingActive = await Booking.findOne({
    $or: [
      { patientMobile: String(patientMobile).trim(), status: { $in: ACTIVE_STATUSES } },
      ...(patientEmail ? [{ patientEmail: String(patientEmail).trim().toLowerCase(), status: { $in: ACTIVE_STATUSES } }] : [])
    ]
  });

  if (existingActive) {
    return fail(res, `Patient already has an active token (${existingActive.tokenId}). A patient can only have one active token at a time.`, 409);
  }

  const finalTokenId = await uniqueWalkinTokenId();

  const booking = await Booking.create({
    tokenId: finalTokenId,
    patientName: String(patientName).trim(),
    patientEmail: patientEmail ? String(patientEmail).trim().toLowerCase() : `walkin-${finalTokenId.toLowerCase()}@queuex.local`,
    patientMobile: String(patientMobile).trim(),
    patientId: null,
    doctorName: doctorName || "General OPD",
    doctorDept: doctorDept || "General Medicine",
    doctorId: null,
    roomNo: "",
    slotTime: timeSlot,
    bookingDate: today,
    status: "CONFIRMED",
    symptoms: {
      primary: symptoms || "Walk-in consultation",
      severity: "Mild",
      duration: "",
      previousProblem: "No"
    },
    address: "",
    distanceKm: 0,
    assistantNote: `Walk-in token generated by ${req.user ? req.user.email : "assistant"}`
  });

  logger.info("WALKIN", `Walk-in token ${finalTokenId} created for ${patientName} (${patientMobile})`);
  eventHub.broadcast("board.updated", { reason: "walkin.created", tokenId: finalTokenId });

  return ok(res, {
    tokenId: booking.tokenId,
    patientName: booking.patientName,
    patientMobile: booking.patientMobile,
    doctorName: booking.doctorName,
    doctorDept: booking.doctorDept,
    bookingDate: booking.bookingDate,
    slotTime: booking.slotTime,
    symptoms: symptoms || "Walk-in consultation",
    status: booking.status,
    createdAt: booking.createdAt
  }, "Walk-in token generated successfully", 201);
});

exports.getAnalytics = ah(async (req, res) => {
  const { period } = req.query;
  const now = new Date();

  let startDate;
  if (period === "weekly") {
    startDate = new Date(now);
    startDate.setDate(startDate.getDate() - 7);
  } else {
    startDate = new Date(now);
    startDate.setMonth(startDate.getMonth() - 1);
  }

  const allBookings = await Booking.find({
    createdAt: { $gte: startDate }
  }).sort({ createdAt: -1 });

  const totalBookings = allBookings.length;
  const statusCounts = {};
  for (const b of allBookings) {
    statusCounts[b.status] = (statusCounts[b.status] || 0) + 1;
  }

  const dailyData = {};
  const dayLabels = [];
  const iterateDate = new Date(startDate);
  while (iterateDate <= now) {
    const dateStr = iterateDate.toISOString().split("T")[0];
    dayLabels.push(dateStr);
    dailyData[dateStr] = { total: 0, PENDING_ASSISTANT: 0, CONFIRMED: 0, PATIENT_ARRIVED: 0, IN_TREATMENT: 0, COMPLETED: 0, REJECTED: 0, CANCELLED: 0, NO_SHOW: 0 };
    iterateDate.setDate(iterateDate.getDate() + 1);
  }

  for (const b of allBookings) {
    const dateStr = b.createdAt.toISOString().split("T")[0];
    if (dailyData[dateStr]) {
      dailyData[dateStr].total++;
      dailyData[dateStr][b.status] = (dailyData[dateStr][b.status] || 0) + 1;
    }
  }

  const dailyBreakdown = dayLabels.map((date) => ({
    date,
    label: new Date(date + "T00:00:00").toLocaleDateString("en-IN", { weekday: "short", day: "numeric", month: "short" }),
    ...dailyData[date]
  }));

  let weeklyBreakdown = null;
  if (period === "monthly") {
    weeklyBreakdown = [];
    const weeksInMonth = [[], [], [], []];
    for (const day of dayLabels) {
      const d = new Date(day + "T00:00:00");
      const weekOfMonth = Math.min(3, Math.floor((d.getDate() - 1) / 7));
      weeksInMonth[weekOfMonth].push(day);
    }
    for (let i = 0; i < 4; i++) {
      const weekDays = weeksInMonth[i];
      const weekStart = weekDays[0];
      const weekEnd = weekDays[weekDays.length - 1];
      let weekTotal = 0;
      let weekCompleted = 0;
      let weekRejected = 0;
      let weekPending = 0;
      for (const d of weekDays) {
        weekTotal += dailyData[d].total;
        weekCompleted += dailyData[d].COMPLETED || 0;
        weekRejected += dailyData[d].REJECTED || 0;
        weekPending += dailyData[d].PENDING_ASSISTANT || 0;
      }
      weeklyBreakdown.push({
        week: i + 1,
        label: weekStart && weekEnd ? `Week ${i + 1} (${new Date(weekStart + "T00:00:00").toLocaleDateString("en-IN", { day: "numeric", month: "short" })} - ${new Date(weekEnd + "T00:00:00").toLocaleDateString("en-IN", { day: "numeric", month: "short" })})` : `Week ${i + 1}`,
        total: weekTotal,
        completed: weekCompleted,
        rejected: weekRejected,
        pending: weekPending,
        days: weekDays.length
      });
    }
  }

  const doctorStats = {};
  for (const b of allBookings) {
    const doc = b.doctorName || "Unknown";
    if (!doctorStats[doc]) doctorStats[doc] = { total: 0, completed: 0 };
    doctorStats[doc].total++;
    if (b.status === "COMPLETED") doctorStats[doc].completed++;
  }

  const doctorBreakdown = Object.entries(doctorStats)
    .map(([name, data]) => ({ name, ...data }))
    .sort((a, b) => b.total - a.total)
    .slice(0, 10);

  return ok(res, {
    period: period || "monthly",
    totalBookings,
    statusCounts,
    dailyBreakdown,
    weeklyBreakdown,
    doctorBreakdown,
    dateRange: {
      from: startDate.toISOString(),
      to: now.toISOString()
    }
  }, "Analytics data");
});

exports.getLiveStats = ah(async (req, res) => {
  const today = new Date().toISOString().split("T")[0];

  const todayBookings = await Booking.countDocuments({ bookingDate: today });
  const totalBookings = await Booking.countDocuments();
  const activeTokens = await Booking.countDocuments({ status: { $in: ACTIVE_STATUSES } });
  const completedToday = await Booking.countDocuments({ bookingDate: today, status: "COMPLETED" });
  const pendingToday = await Booking.countDocuments({ bookingDate: today, status: "PENDING_ASSISTANT" });
  const confirmedToday = await Booking.countDocuments({ bookingDate: today, status: "CONFIRMED" });

  const allUsers = await User.countDocuments({ active: true });
  const recentLogins = await User.countDocuments({
    lastLogin: { $gte: new Date(Date.now() - 30 * 60 * 1000) },
    active: true
  });

  return ok(res, {
    todayBookings,
    totalBookings,
    activeTokens,
    completedToday,
    pendingToday,
    confirmedToday,
    totalRegisteredPatients: allUsers,
    activeLogins: recentLogins,
    timestamp: new Date().toISOString()
  }, "Live statistics");
});

exports.checkActiveToken = ah(async (req, res) => {
  const { email, mobile } = req.query;
  if (!email && !mobile) {
    return ok(res, { hasActive: false });
  }

  const query = { status: { $in: ACTIVE_STATUSES } };
  if (email) query.patientEmail = String(email).trim().toLowerCase();
  if (mobile) query.patientMobile = String(mobile).trim();

  const active = await Booking.findOne(query).sort({ createdAt: -1 });
  return ok(res, {
    hasActive: !!active,
    activeToken: active ? {
      tokenId: active.tokenId,
      doctorName: active.doctorName,
      bookingDate: active.bookingDate,
      slotTime: active.slotTime,
      status: active.status,
      createdAt: active.createdAt
    } : null
  });
});

exports.getWalkinHistory = ah(async (req, res) => {
  const walkins = await Booking.find({
    tokenId: { $regex: /^QX-8/ }
  }).sort({ createdAt: -1 }).limit(200);
  return ok(res, walkins, "Walk-in patient history");
});

exports.getWalkinPassPdf = ah(async (req, res) => {
  const { tokenId } = req.params;
  if (!tokenId) {
    return fail(res, "Token ID is required", 400);
  }

  const booking = await Booking.findOne({ tokenId: String(tokenId).trim() });
  if (!booking) {
    return fail(res, "Token not found", 404);
  }
  if (!booking.tokenId.startsWith("QX-8")) {
    return fail(res, "PDF pass is only available for walk-in tokens", 400);
  }

  const symptoms = booking.symptoms && booking.symptoms.primary
    ? booking.symptoms.primary
    : "Walk-in consultation";

  const pdfBuffer = await generateWalkinPass({
    tokenId: booking.tokenId,
    patientName: booking.patientName,
    patientMobile: booking.patientMobile,
    doctorName: booking.doctorName,
    doctorDept: booking.doctorDept,
    bookingDate: booking.bookingDate,
    slotTime: booking.slotTime,
    symptoms
  });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="walkin-pass-${booking.tokenId}.pdf"`);
  res.setHeader("Content-Length", pdfBuffer.length);
  return res.send(pdfBuffer);
});
